### ISSUE TITLE
vite开发环境运行会报错

### ISSUE THREAD

**Issue by ll60** [gitbrent/xlsx-js-style#10]
在dev模式下，会报下面的错误。但是在预览环境或者打包正式环境不会出现问题，请问有遇到过吗

vue-router.mjs:3441 Error: Module "stream" has been externalized for browser compatibility. Cannot access "stream.Readable" in client code.
    at Object.get (browser-external:stream:9:13)
    at make_xlsx_lib (xlsx.min.js:2:424100)
    at node_modules/.pnpm/xlsx-js-style@1.2.0/node_modules/xlsx-js-style/dist/xlsx.min.js (xlsx.min.js:2:424157)
    at __require2 (chunk-NKHIPFFU.js?v=2d1bd263:15:50)
    at dep:xlsx-js-style:1:16

**Comment by ll60** [comment]
没有问题了，vite3.1更新了这个问题，错误成都降低为警告了。

**Comment by stalkercn** [comment]
https://github.com/SheetJS/sheetjs/pull/2744
xlsx-js solved this problem by adding exports fields to package.json. @ll60
